import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Form, Formik, useField } from 'formik';
import { useRouter } from 'next/router';

const MyTextInput = ({ label, ...props }) => {
  const [field, meta] = useField(props);
  return (
    <>
      <label htmlFor={props.id || props.name}>{label}</label>
      <input className="text-input" {...field} {...props} />
      {meta.touched && meta.error ? (
        <div className="error">{meta.error}</div>
      ) : null}
    </>
  );
};

export default function Home() {
  const router = useRouter()

  const handleSubmit = (values) => {
    console.log("form values", values);
    router.push(`/${values.name}`)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <Formik initialValues={{name: ""}} onSubmit={handleSubmit}>
            <Form>
              <MyTextInput
                label="Name"
                name="name"
                type="text"
                placeholder="Enter Name"
              />

              <button type="submit"> Submit </button>
            </Form>
          </Formik>
        </div>
      </main>
    </>
  )
}
